final List<Map<String, String>> allahNames = [
  {"arabic": "ٱلْرَّحْمَـٰنُ", "transliteration": "AR-RAHMAAN", "translation": "The Most or Entirely Merciful"},
  {"arabic": "ٱلْرَّحِيمُ", "transliteration": "AR-RAHEEM", "translation": "The Bestower of Mercy"},
  {"arabic": "ٱلْمَلِكُ", "transliteration": "AL-MALIK", "translation": "The King and Owner of Dominion"},
  {"arabic": "ٱلْقُدُّوسُ", "transliteration": "AL-QUDDUS", "translation": "The Absolutely Pure"},
  {"arabic": "ٱلْسَّلَامُ", "transliteration": "AS-SALAM", "translation": "The Perfection and Giver of Peace"},
  {"arabic": "ٱلْمُؤْمِنُ", "transliteration": "AL-MU’MIN", "translation": "The One Who gives Emaan and Security"},
  {"arabic": "ٱلْمُهَيْمِنُ", "transliteration": "AL-MUHAYMIN", "translation": "The Guardian, The Witness, The Overseer"},
  {"arabic": "ٱلْعَزِيزُ", "transliteration": "AL-AZEEZ", "translation": "The All Mighty"},
  {"arabic": "ٱلْجَبَّارُ", "transliteration": "AL-JABBAR", "translation": "The Compeller, The Restorer"},
  {"arabic": "ٱلْمُتَكَبِّرُ", "transliteration": "AL-MUTAKABBIR", "translation": "The Supreme, The Majestic"},
  {"arabic": "ٱلْخَالِقُ", "transliteration": "AL-KHAALIQ", "translation": "The Creator, The Maker"},
  {"arabic": "ٱلْبَارِئُ", "transliteration": "AL-BAARI’", "translation": "The Originator"},
  {"arabic": "ٱلْمُصَوِّرُ", "transliteration": "AL-MUSAWWIR", "translation": "The Fashioner"},
  {"arabic": "ٱلْغَفَّارُ", "transliteration": "AL-GHAFFAR", "translation": "The All- and Oft-Forgiving"},
  {"arabic": "ٱلْقَهَّارُ", "transliteration": "AL-QAHHAR", "translation": "The Subduer, The Ever-Dominating"},
  {"arabic": "ٱلْوَهَّابُ", "transliteration": "AL-WAHHAAB", "translation": "The Giver of Gifts"},
  {"arabic": "ٱلْرَّزَّاقُ", "transliteration": "AR-RAZZAAQ", "translation": "The Provider"},
  {"arabic": "ٱلْفَتَّاحُ", "transliteration": "AL-FATTAAH", "translation": "The Opener, The Judge"},
  {"arabic": "ٱلْعَلِيمُ", "transliteration": "AL-‘ALEEM", "translation": "The All-Knowing, The Omniscient"},
  {"arabic": "ٱلْقَابِضُ", "transliteration": "AL-QAABID", "translation": "The Withholder"},
  {"arabic": "ٱلْبَاسِطُ", "transliteration": "AL-BAASIT", "translation": "The Extender"},
  {"arabic": "ٱلْخَافِضُ", "transliteration": "AL-KHAAFIDH", "translation": "The Reducer, The Abaser"},
  {"arabic": "ٱلْرَّافِعُ", "transliteration": "AR-RAAFI’", "translation": "The Exalter, The Elevator"},
  {"arabic": "ٱلْمُعِزُّ", "transliteration": "AL-MU’IZZ", "translation": "The Honourer, The Bestower"},
  {"arabic": "ٱلْمُذِلُّ", "transliteration": "AL-MUZIL", "translation": "The Dishonourer, The Humiliator"},
  {"arabic": "ٱلْسَّمِيعُ", "transliteration": "AS-SAMEE’", "translation": "The All-Hearing"},
  {"arabic": "ٱلْبَصِيرُ", "transliteration": "AL-BASEER", "translation": "The All-Seeing"},
  {"arabic": "ٱلْحَكَمُ", "transliteration": "AL-HAKAM", "translation": "The Judge, The Giver of Justice"},
  {"arabic": "ٱلْعَدْلُ", "transliteration": "AL-‘ADL", "translation": "The Utterly Just"},
  {"arabic": "ٱلْلَّطِيفُ", "transliteration": "AL-LATEEF", "translation": "The Subtle One, The Most Gentle"},
  {"arabic": "ٱلْخَبِيرُ", "transliteration": "AL-KHABEER", "translation": "The Acquainted, the All-Aware"},
  {"arabic": "ٱلْحَلِيمُ", "transliteration": "AL-HALEEM", "translation": "The Most Forbearing"},
  {"arabic": "ٱلْعَظِيمُ", "transliteration": "AL-‘ATHEEM", "translation": "The Magnificent, The Supreme"},
  {"arabic": "ٱلْغَفُورُ", "transliteration": "AL-GHAFOOR", "translation": "The Forgiving, The Exceedingly Forgiving"},
  {"arabic": "ٱلْشَّكُورُ", "transliteration": "ASH-SHAKOOR", "translation": "The Most Appreciative"},
  {"arabic": "ٱلْعَلِيُّ", "transliteration": "AL-‘ALEE", "translation": "The Most High, The Exalted"},
  {"arabic": "ٱلْكَبِيرُ", "transliteration": "AL-KABEER", "translation": "The Greatest, The Most Grand"},
  {"arabic": "ٱلْحَفِيظُ", "transliteration": "AL-HAFEEDH", "translation": "The Preserver, The All-Heedful and All-Protecting"},
  {"arabic": "ٱلْمُقِيتُ", "transliteration": "AL-MUQEET", "translation": "The Sustainer"},
  {"arabic": "ٱلْحَسِيبُ", "transliteration": "AL-HASEEB", "translation": "The Reckoner, The Sufficient"},
  {"arabic": "ٱلْجَلِيلُ", "transliteration": "AL-JALEEL", "translation": "The Majestic"},
  {"arabic": "ٱلْكَرِيمُ", "transliteration": "AL-KAREEM", "translation": "The Most Generous, The Most Esteemed"},
  {"arabic": "ٱلْرَّقِيبُ", "transliteration": "AR-RAQEEB", "translation": "The Watchful"},
  {"arabic": "ٱلْمُجِيبُ", "transliteration": "AL-MUJEEB", "translation": "The Responsive One"},
  {"arabic": "ٱلْوَاسِعُ", "transliteration": "AL-WAASI’", "translation": "The All-Encompassing, the Boundless"},
  {"arabic": "ٱلْحَكِيمُ", "transliteration": "AL-HAKEEM", "translation": "The All-Wise"},
  {"arabic": "ٱلْوَدُودُ", "transliteration": "AL-WADOOD", "translation": "The Most Loving"},
  {"arabic": "ٱلْمَجِيدُ", "transliteration": "AL-MAJEED", "translation": "The Glorious, The Most Honorable"},
  {"arabic": "ٱلْبَاعِثُ", "transliteration": "AL-BA’ITH", "translation": "The Resurrector, The Raiser of the Dead"},
  {"arabic": "ٱلْشَّهِيدُ", "transliteration": "ASH-SHAHEED", "translation": "The All- and Ever Witnessing"},
  {"arabic": "ٱلْحَقُّ", "transliteration": "AL-HAQQ", "translation": "The Absolute Truth"},
  {"arabic": "ٱلْوَكِيلُ", "transliteration": "AL-WAKEEL", "translation": "The Trustee, The Disposer of Affairs"},
  {"arabic": "ٱلْقَوِيُّ", "transliteration": "AL-QAWIYY", "translation": "The All-Strong"},
  {"arabic": "ٱلْمَتِينُ", "transliteration": "AL-MATEEN", "translation": "The Firm, The Steadfast"},
  {"arabic": "ٱلْوَلِيُّ", "transliteration": "AL-WALIYY", "translation": "The Protecting Associate"},
  {"arabic": "ٱلْحَمِيدُ", "transliteration": "AL-HAMEED", "translation": "The Praiseworthy"},
  {"arabic": "ٱلْمُحْصِيُ", "transliteration": "AL-MUHSEE", "translation": "The All-Enumerating, The Counter"},
  {"arabic": "ٱلْمُبْدِئُ", "transliteration": "AL-MUBDI", "translation": "The Originator, The Initiator"},
  {"arabic": "ٱلْمُعِيدُ", "transliteration": "AL-MU’ID", "translation": "The Restorer, The Reinstater"},
  {"arabic": "ٱلْمُحْيِى", "transliteration": "AL-MUHYEE", "translation": "The Giver of Life"},
  {"arabic": "ٱلْمُمِيتُ", "transliteration": "AL-MUMEET", "translation": "The Bringer of Death, the Destroyer"},
  {"arabic": "ٱلْحَىُّ", "transliteration": "AL-HAYY", "translation": "The Ever-Living"},
  {"arabic": "ٱلْقَيُّومُ", "transliteration": "AL-QAYYOOM", "translation": "The Sustainer, The Self-Subsisting"},
  {"arabic": "ٱلْوَاجِدُ", "transliteration": "AL-WAAJID", "translation": "The Perceiver"},
  {"arabic": "ٱلْمَاجِدُ", "transliteration": "AL-MAAJID", "translation": "The Illustrious, the Magnificent"},
  {"arabic": "ٱلْوَاحِدُ", "transliteration": "AL-WAAHID", "translation": "The One"},
  {"arabic": "ٱلْأَحَد", "transliteration": "AL-AHAD", "translation": "The Unique, The Only One"},
  {"arabic": "ٱلْصَّمَدُ", "transliteration": "AS-SAMAD", "translation": "The Eternal, Satisfier of Needs"},
  {"arabic": "ٱلْقَادِرُ", "transliteration": "AL-QADEER", "translation": "The Capable, The Powerful"},
  {"arabic": "ٱلْمُقْتَدِرُ", "transliteration": "AL-MUQTADIR", "translation": "The Omnipotent"},
  {"arabic": "ٱلْمُقَدِّمُ", "transliteration": "AL-MUQADDIM", "translation": "The Expediter, The Promoter"},
  {"arabic": "ٱلْمُؤَخِّرُ", "transliteration": "AL-MU’AKHKHIR", "translation": "The Delayer, the Retarder"},
  {"arabic": "ٱلْأَوَّلُ", "transliteration": "AL-AWWAL", "translation": "The First"},
  {"arabic": "ٱلْآخِرُ", "transliteration": "AL-AAKHIR", "translation": "The Last"},
  {"arabic": "ٱلْظَّاهِرُ", "transliteration": "AZ-DHAAHIR", "translation": "The Manifest"},
  {"arabic": "ٱلْبَاطِنُ", "transliteration": "AL-BAATIN", "translation": "The Hidden One, Knower of the Hidden"},
  {"arabic": "ٱلْوَالِي", "transliteration": "AL-WAALI", "translation": "The Governor, The Patron"},
  {"arabic": "ٱلْمُتَعَالِي", "transliteration": "AL-MUTA’ALI", "translation": "The Self Exalted"},
  {"arabic": "ٱلْبَرُّ", "transliteration": "AL-BARR", "translation": "The Source of Goodness, the Kind Benefactor"},
  {"arabic": "ٱلْتَّوَّابُ", "transliteration": "AT-TAWWAB", "translation": "The Ever-Pardoning, The Relenting"},
  {"arabic": "ٱلْمُنْتَقِمُ", "transliteration": "AL-MUNTAQIM", "translation": "The Avenger"},
  {"arabic": "ٱلْعَفُوُّ", "transliteration": "AL-‘AFUWW", "translation": "The Pardoner"},
  {"arabic": "ٱلْرَّؤُفُ", "transliteration": "AR-RA’OOF", "translation": "The Most Kind"},
  {"arabic": "مَالِكُ ٱلْمُلْكُ", "transliteration": "MAALIK-UL-MULK", "translation": "Master of the Kingdom, Owner of the Dominion"},
  {"arabic": "ذُو ٱلْجَلَالِ وَٱلْإِكْرَامُ", "transliteration": "DHUL-JALAALI WAL-IKRAAM", "translation": "Possessor of Glory and Honour, Lord of Majesty and Generosity"},
  {"arabic": "ٱلْمُقْسِطُ", "transliteration": "AL-MUQSIT", "translation": "The Equitable, the Requiter"},
  {"arabic": "ٱلْجَامِعُ", "transliteration": "AL-JAAMI’", "translation": "The Gatherer, the Uniter"},
  {"arabic": "ٱلْغَنيُّ", "transliteration": "AL-GHANIYY", "translation": "The Self-Sufficient, The Wealthy"},
  {"arabic": "ٱلْمُغْنِيُّ", "transliteration": "AL-MUGHNI", "translation": "The Enricher"},
  {"arabic": "ٱلْمَانِعُ", "transliteration": "AL-MANI’", "translation": "The Withholder"},
  {"arabic": "ٱلْضَّارُ", "transliteration": "AD-DHARR", "translation": "The Distresser"},
  {"arabic": "ٱلْنَّافِعُ", "transliteration": "AN-NAFI’", "translation": "The Propitious, the Benefactor"},
  {"arabic": "ٱلْنُّورُ", "transliteration": "AN-NUR", "translation": "The Light, The Illuminator"},
  {"arabic": "ٱلْهَادِي", "transliteration": "AL-HAADI", "translation": "The Guide"},
  {"arabic": "ٱلْبَدِيعُ", "transliteration": "AL-BADEE’", "translation": "The Incomparable Originator"},
  {"arabic": "ٱلْبَاقِي", "transliteration": "AL-BAAQI", "translation": "The Ever-Surviving, The Everlasting"},
  {"arabic": "ٱلْوَارِثُ", "transliteration": "AL-WAARITH", "translation": "The Inheritor, The Heir"},
  {"arabic": "ٱلْرَّشِيدُ", "transliteration": "AR-RASHEED", "translation": "The Guide, Infallible Teacher"},
  {"arabic": "ٱلْصَّبُورُ", "transliteration": "AS-SABOOR", "translation": "The Forbearing, The Patient"},
];



 const String jakatText="""
In Islam, Zakat is one of the Five Pillars and is a mandatory act of charity for eligible Muslims. It is a way to purify wealth and help those in need. The Quran and Hadith emphasize the importance of giving Zakat to support the poor, orphans, debt-ridden individuals, and other eligible recipients.
How Much Zakat to Give?
Muslims who meet the Nisab threshold (minimum amount of wealth required) must give 2.5% (1/40th) of their savings, gold, silver, and other assets that have been held for a lunar year. The Nisab is based on:
Gold: 85 grams (approx.)
Silver: 595 grams (approx.)
If someone possesses wealth above this limit after their necessary expenses, they must pay Zakat on it. Other forms of wealth, like agricultural produce, livestock, and business profits, have different Zakat rates.
Zakat serves as a means to redistribute wealth, promote social justice, and purify one's earnings.
""";